---

- name: install mariadb
  yum: pkg={{ item }} state=latest
  with_items:
    - mariadb
    - mariadb-server
    - MySQL-python

- name: start mariadb service
  service: name=mariadb state=started enabled=yes

